# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc91215336be888d1be22bb0c3e1ac45590150a89e3074224e9b547f8b963c8bab6b6304b3adfa7f3d68220293b68391e0aff19da4100abd63317b676f690302

test:
  secret_key_base: bb8e05d9c21aa1994fa3c85e9e455f501eee00ba9545ac6b93ada77c94d51b8dc420446907f2c12aa04e3e13567e00515f55b68b08f4eb62e8b5f6e54d725637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
